### ISSUE TITLE
Your Blog redirects to an AV site, notice

### ISSUE THREAD

**Issue by CrystalRays** [icecliffs/icecliffs.github.io#1]
your blog blog.icecliffs rediects to an AV site, please correct this or remove the link in your page.

**Comment by mocusez** [comment]
> your blog blog.icecliffs rediects to an AV site, please correct this or remove the link in your page.

It seem his blog move to https://iloli.moe/

**Comment by icecliffs** [comment]
I am no longer using the blog.icecliffs site. Thank you for the reminder
